name: doctor_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  # A build system for Dart code generation and modular compilation.
  build_runner: ^2.10.4
  # state managment
  flutter_bloc: ^9.1.1
  # code generator ( mainly with cubit & retrofit)
  freezed: ^3.2.3
  freezed_annotation: ^3.1.0
  # Dependency injection
  get_it: ^9.1.0
  # Automatically generate code for converting to and from JSON by annotating Dart classes.
  json_serializable: ^6.11.2
  json_annotation: ^4.9.0
  # Networking
  dio: ^5.9.0
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.9.1
  retrofit_generator: ^10.2.0
  # localization
  intl: ^0.20.2
  easy_localization: ^3.0.8
  # splash screen
  flutter_native_splash: ^2.4.7
  # SVG support
  flutter_svg: ^2.2.3
  # for adaptive screen and font size
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets: 
   - assets/images/
   - assets/svgs/
